package ru.aurafx.design;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.content.Intent;
import android.net.Uri;
import android.graphics.Color;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.BitmapFactory;
import android.graphics.drawable.GradientDrawable;
import android.view.View;
import android.view.Gravity;
import android.view.ViewGroup;
import android.view.MotionEvent;
import android.graphics.LinearGradient;
import android.graphics.Shader;
import android.animation.ObjectAnimator;
import android.animation.ValueAnimator;
import android.view.animation.AccelerateDecelerateInterpolator;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.net.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.*;

public class MainActivity extends Activity {
  private static final String BASE="https://aurafx-design.ru";
  private static final String[] CASE_NAMES={"Беспроводные наушники","NOIR","Oversize","Смарт-часы","Портативная колонка","Механическая клавиатура","Городской рюкзак","Кроссовки","Настольная лампа","Термобутылка","Сумка кросс-боди","Кофе в зёрнах","Щётка для лица","Автопылесос","Автокормушка","Ортопедическая подушка","Магнитный конструктор","Термокружка","Чёрный свитшот"};
  private static final String[] CASE_COVERS={"case-00-cover.webp","case-01-cover.webp","case-02-cover.webp","case-03-cover.webp","case-04-cover.webp","case-05-cover.webp","case-06-cover.webp","case-07-cover.webp","case-08-cover.webp","case-09-cover.webp","case-10-cover.webp","case-11-cover.webp","face-brush.webp","car-vacuum.webp","pet-feeder.webp","memory-pillow.webp","magnetic-builder.webp","travel-mug.webp","sweatshirt-slide-01.webp"};
  private static final String[] CASE_CATEGORIES={"Техника","Красота","Одежда","Техника","Техника","Техника","Одежда","Одежда","Для дома","Для дома","Одежда","Продукты","Красота","Авто","Питомцы","Для дома","Детям","В дорогу","Одежда"};
  private static final String[] CASE_DETAILS={"Автономность, микрофон и шумоподавление","Аромат и акцент на флаконе","Материал, силуэт и детали ткани","AMOLED · до 7 дней · IP68","20 Вт · до 12 часов · IPX7","68 клавиш · RGB · USB-C","20 л · ноутбук 15,6″","Размеры 36–44 · лёгкая подошва","3 режима света · сенсор","500 мл · сталь 304","Экокожа · 2 отделения","100% арабика · 250 г","3 режима · IPX7","12 000 Па · HEPA","4 л · до 6 кормлений","Memory Foam · поддержка шеи","64 детали · крупные элементы","500 мл · до 8 часов","Обложка, детали, материал и образ"};
  private static final int BG=0xff1d112e, PANEL=0xff251733, WHITE=0xfff8f3ff, MUTED=0xffbdb0c9, VIOLET=0xff9b4dff, CYAN=0xff70e6f6;
  private final ExecutorService pool=Executors.newFixedThreadPool(3);
  private final Handler main=new Handler(Looper.getMainLooper());
  private LinearLayout page,root,nav;
  private final android.util.LruCache<String,android.graphics.Bitmap> images=new android.util.LruCache<>(18);
  private final java.util.ArrayList<ValueAnimator> motion=new java.util.ArrayList<>();
  private String session="", loginToken="";
  private int current=0, loginTries=0;
  private boolean owner=false;
  private int adminGeneration=0;
  private boolean active=true;
  private interface Done { void accept(JSONObject data, Exception error); }

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);session=getPreferences(0).getString("session","");render(0);}
  @Override protected void onDestroy(){active=false;for(ValueAnimator animator:motion)animator.cancel();pool.shutdownNow();super.onDestroy();}
  @Override public void onBackPressed(){if(current!=0)render(0);else super.onBackPressed();}
  private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  private GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));g.setStroke(dp(1),0xff453453);return g;}
  private GradientDrawable glow(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff682abe,0xff302358,0xff14506b});g.setCornerRadius(dp(24));return g;}
  private TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(null,1);t.setLineSpacing(dp(3),1);return t;}
  private void add(LinearLayout box,View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(top);box.addView(v,p);}
  private LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);return c;}
  private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(shape(PANEL,22));return c;}
  private void title(String kicker,String heading,String sub){add(page,text(kicker.toUpperCase(),12,CYAN,true),8);add(page,text(heading,32,WHITE,true),10);if(sub!=null)add(page,text(sub,15,MUTED,false),9);}
  private Button button(String label,boolean primary,Runnable action){Button b=new Button(this);b.setAllCaps(false);b.setText(label);b.setTextSize(15);b.setTextColor(WHITE);b.setBackground(primary?glow():shape(0xff292035,16));b.setOnClickListener(v->action.run());return b;}
  private EditText field(String hint,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(0xff8f81a0);e.setTextColor(WHITE);e.setTextSize(15);e.setSingleLine(!multi);if(multi)e.setMinLines(3);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(shape(0xff261d32,14));return e;}
  private Spinner selector(String[] values){Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,values){@Override public View getView(int position,View old,ViewGroup parent){TextView v=(TextView)super.getView(position,old,parent);v.setTextColor(WHITE);v.setTextSize(15);return v;}@Override public View getDropDownView(int position,View old,ViewGroup parent){TextView v=(TextView)super.getDropDownView(position,old,parent);v.setTextColor(0xff211329);return v;}};s.setAdapter(a);s.setBackground(shape(0xff30213f,14));s.setPadding(dp(12),dp(8),dp(12),dp(8));return s;}
  private String value(EditText e){return e.getText().toString().trim();}
  private void message(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
  private void floatView(View v,int delay,int distance){if(!ValueAnimator.areAnimatorsEnabled())return;ObjectAnimator a=ObjectAnimator.ofFloat(v,"translationY",0,-dp(distance),0);a.setDuration(4200);a.setStartDelay(delay);a.setInterpolator(new AccelerateDecelerateInterpolator());a.setRepeatCount(ValueAnimator.INFINITE);motion.add(a);a.start();}
  private void enter(View v,int delay){if(!ValueAnimator.areAnimatorsEnabled())return;v.setAlpha(0f);v.setTranslationY(dp(18));v.animate().alpha(1f).translationY(0f).setStartDelay(delay).setDuration(440).start();}
  private final class IconGlyph extends View {
    private final int kind,color;private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private final Path path=new Path();
    IconGlyph(int kind,int color){super(MainActivity.this);this.kind=kind;this.color=color;setContentDescription(new String[]{"Главная","Кейсы","Заказ","Кабинет","Поддержка","Услуги","Тарифы","Отзывы","Разбор","План","Пульт студии"}[kind]);}
    private void line(Canvas c,float... xy){path.reset();path.moveTo(xy[0],xy[1]);for(int i=2;i<xy.length;i+=2)path.lineTo(xy[i],xy[i+1]);c.drawPath(path,paint);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);int save=c.save();float scale=Math.min(getWidth(),getHeight())/32f;c.translate((getWidth()-32*scale)/2f,(getHeight()-32*scale)/2f);c.scale(scale,scale);paint.setColor(color);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(2.2f);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);
      switch(kind){
        case 0:line(c,4,15,16,5,28,15);line(c,8,13,8,27,24,27,24,13);line(c,14,27,14,19,19,19,19,27);break;
        case 1:c.drawRoundRect(new RectF(5,5,14,14),2,2,paint);c.drawRoundRect(new RectF(18,5,27,14),2,2,paint);c.drawRoundRect(new RectF(5,18,14,27),2,2,paint);c.drawRoundRect(new RectF(18,18,27,27),2,2,paint);break;
        case 2:c.drawRoundRect(new RectF(5,8,27,27),3,3,paint);line(c,5,14,27,14);line(c,15,21,21,21);line(c,18,18,18,24);break;
        case 3:c.drawCircle(16,11,5,paint);c.drawArc(new RectF(5,17,27,31),180,180,false,paint);break;
        case 4:c.drawRoundRect(new RectF(4,5,28,23),5,5,paint);line(c,10,23,9,28,17,23);line(c,10,12,22,12);line(c,10,17,18,17);break;
        case 5:c.drawCircle(16,16,10,paint);line(c,16,3,16,8);line(c,16,24,16,29);line(c,3,16,8,16);line(c,24,16,29,16);c.drawCircle(16,16,3,paint);break;
        case 6:line(c,17,3,7,18,15,18,12,29,26,12,18,12,17,3);break;
        case 7:for(int i=0;i<10;i++){double a=-Math.PI/2+i*Math.PI/5;float r=i%2==0?12:5;float x=16+(float)Math.cos(a)*r,y=16+(float)Math.sin(a)*r;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}path.close();c.drawPath(path,paint);break;
        case 8:c.drawCircle(14,14,9,paint);line(c,21,21,29,29);line(c,14,10,14,18);line(c,10,14,18,14);break;
        case 9:c.drawRoundRect(new RectF(7,4,25,28),3,3,paint);line(c,12,11,20,11);line(c,12,16,20,16);line(c,12,21,17,21);break;
        case 10:line(c,16,3,27,8,26,19,22,25,16,29,10,25,6,19,5,8,16,3);line(c,12,16,15,19,21,13);break;
      }c.restoreToCount(save);
    }
  }
  private View icon(int kind,int color,int size){IconGlyph v=new IconGlyph(kind,color);v.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return v;}
  private TextView gradientText(String value,int size){TextView t=text(value,size,WHITE,true);t.getPaint().setShader(new LinearGradient(0,0,dp(280),0,new int[]{CYAN,0xffd49bff,VIOLET},null,Shader.TileMode.CLAMP));return t;}
  private void showMenu(){android.app.Dialog dialog=new android.app.Dialog(this);LinearLayout panel=column();panel.setPadding(dp(22),dp(20),dp(22),dp(22));GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff291544,0xff1b112a,0xff111023});panel.setBackground(bg);ScrollView scroll=new ScrollView(this);scroll.addView(panel);dialog.setContentView(scroll);android.view.Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);window.setDimAmount(.65f);window.setLayout(-1,-1);window.setGravity(Gravity.RIGHT);}
    add(panel,gradientText("✦ AuraFX",32),12);add(panel,text("Меню приложения",16,MUTED,false),7);add(panel,button("✕  Закрыть",false,dialog::dismiss),16);
    String[] names={"Главная","Портфолио","Услуги","Тарифы","Заказать дизайн","Отзывы","Бесплатный разбор","Quick Plan","Личный кабинет","Поддержка","Пульт студии"};String[] captions={"Начало и лучшие работы","19 кейсов по категориям","Что входит в дизайн","Пакеты и срочный срок","Заявка в общую админку","Мнения клиентов","Идея обложки и точки роста","План пяти слайдов","Заказы через Telegram","Переписка с AuraFX","Заявки, отзывы и обращения владельца"};int[] symbols={0,1,5,6,2,7,8,9,3,4,10};Runnable[] actions={()->render(0),()->render(1),this::services,()->render(2),()->render(3),()->render(4),this::audit,this::quickPlan,()->render(5),this::supportEntry,this::adminEntry};
    for(int i=0;i<names.length;i++){if(i==10&&!owner)continue;final int index=i;LinearLayout item=new LinearLayout(this);item.setGravity(Gravity.CENTER_VERTICAL);item.setPadding(dp(15),dp(12),dp(15),dp(12));item.setBackground(i==4||i==10?glow():shape(PANEL,19));IconGlyph glyph=new IconGlyph(symbols[i],i==4?WHITE:CYAN);item.addView(glyph,new LinearLayout.LayoutParams(dp(32),dp(32)));LinearLayout copy=column();add(copy,text(names[i],17,WHITE,true),0);add(copy,text(captions[i],12,MUTED,false),3);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.leftMargin=dp(13);item.addView(copy,cp);add(panel,item,9);item.setOnClickListener(v->{dialog.dismiss();actions[index].run();});}dialog.show();if(window!=null)window.setLayout(-1,-1);}
  private void supportEntry(){request("GET","/api/auth/me",null,(d,e)->{if(e==null&&d.optBoolean("authenticated"))support();else{message("Войди через Telegram, чтобы открыть поддержку.");render(5);}});}
  private void render(int tab){for(ValueAnimator animator:motion)animator.cancel();motion.clear();current=tab;root=column();root.setBackgroundColor(BG);setContentView(root);
    LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(18),dp(12),dp(16),dp(10));TextView brand=gradientText("✦ AuraFX",23);header.addView(brand,new LinearLayout.LayoutParams(0,dp(52),1));brand.setGravity(Gravity.CENTER_VERTICAL);floatView(brand,0,3);
    Button menu=button("☰  Меню",false,this::showMenu);menu.setTextSize(13);header.addView(menu,new LinearLayout.LayoutParams(dp(112),dp(45)));root.addView(header);
    ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setVerticalScrollBarEnabled(false);page=column();page.setPadding(dp(20),0,dp(20),dp(30));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);nav.setPadding(dp(6),0,dp(6),0);nav.setBackgroundColor(0xff180e26);int[] targets={0,1,3,5};int[] symbols={0,1,2,3};String[] labels={"Студия","Кейсы","Заявка","Кабинет"};for(int i=0;i<targets.length;i++){final int index=targets[i];boolean selected=index==tab;LinearLayout item=column();item.setGravity(Gravity.CENTER);IconGlyph glyph=new IconGlyph(symbols[i],selected?CYAN:MUTED);item.addView(glyph,new LinearLayout.LayoutParams(dp(25),dp(25)));TextView caption=text(labels[i],11,selected?WHITE:MUTED,selected);caption.setGravity(Gravity.CENTER);add(item,caption,3);nav.addView(item,new LinearLayout.LayoutParams(0,dp(66),1));item.setOnClickListener(v->render(index));}root.addView(nav);
    switch(tab){case 0:home();break;case 1:work();break;case 2:prices();break;case 3:order();break;case 4:reviews();break;default:account();}}
  private void home(){
    add(page,text("AURAFX  /  CREATIVE STUDIO",12,CYAN,true),18);
    LinearLayout editorial=column();editorial.setPadding(dp(22),dp(22),dp(22),dp(22));editorial.setBackground(glow());
    add(editorial,text("СТУДИЯ В ТВОЁМ КАРМАНЕ  ✦",12,0xffe5d4ff,true),0);
    add(editorial,text("Есть товар.\nНайдём его сильный кадр.",28,WHITE,true),13);
    add(editorial,text("От идеи первого экрана до готовой серии. Начни с плана, а дальше соберём дизайн вместе.",15,0xffeee2f9,false),13);
    add(editorial,button("Начать с идеи  ↗",true,this::quickPlan),18);
    add(page,editorial,16);enter(editorial,80);
    add(page,text("ТВОЙ МАРШРУТ",12,CYAN,true),26);
    LinearLayout route=card();add(route,text("01  Идея  →  02  Визуал  →  03  Запуск",17,WHITE,true),0);add(route,text("Спланируй серию, выбери стиль в кейсах и отправь короткий бриф.",14,MUTED,false),9);add(page,route,9);
    add(page,text("✦  ДИЗАЙН ДЛЯ МАРКЕТПЛЕЙСОВ",12,CYAN,true),27);TextView h=text("Карточки, которые",36,WHITE,true);add(page,h,20);add(page,gradientText("цепляют взгляд",39),0);add(page,text("Обложка и серия инфографики для WB, Ozon и Avito. Покажем преимущества товара на каждом слайде.",16,MUTED,false),17);
    add(page,button("Обсудить товар  →",true,()->render(3)),22);add(page,button("Смотреть работы",false,()->render(1)),10);
    FrameLayout showcase=new FrameLayout(this);showcase.setClipChildren(false);String[] hero={CASE_COVERS[0],CASE_COVERS[2],CASE_COVERS[1]};int[] widths={175,180,175},left={0,74,146},top={28,74,36};float[] angles={-9,0,10};for(int i=0;i<3;i++){ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackground(shape(PANEL,20));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(widths[i]),dp(245));p.leftMargin=dp(left[i]);p.topMargin=dp(top[i]);showcase.addView(im,p);im.setRotation(angles[i]);im.setElevation(dp(9+i*3));image(hero[i],im);floatView(im,i*370,8+i*2);}page.addView(showcase,new LinearLayout.LayoutParams(-1,dp(350)));
    LinearLayout stats=card();stats.setBackground(glow());add(stats,text("2–4 дня  ·  от 24 часов срочно",16,WHITE,true),0);add(stats,text("2 круга правок включены  •  срочный срок +50%",13,WHITE,false),8);add(page,stats,2);
    add(page,text("Что входит",24,WHITE,true),29);String[][] services={{"01 / АНАЛИЗ","Разбор ниши","Смотрим товар и конкурентов."},{"02 / СТРУКТУРА","Инфографика","Выносим ключевые преимущества."},{"03 / ВИЗУАЛ","Обработка","Композиция, цвет и детали."},{"04 / ВЫДАЧА","Готовые файлы","Нужные форматы для площадки."}};for(int i=0;i<services.length;i++){LinearLayout c=card();add(c,text(services[i][0],12,CYAN,true),0);add(c,text(services[i][1],20,WHITE,true),8);add(c,text(services[i][2],14,MUTED,false),5);add(page,c,10);enter(c,100+i*100);}
    add(page,button("◇  Бесплатный мини-разбор",true,this::audit),24);add(page,button("✧  Собрать план пяти слайдов",false,this::quickPlan),10);add(page,button("Тарифы и сроки",false,()->render(2)),10);add(page,button("Отзывы клиентов",false,()->render(4)),10);if(owner)add(page,button("◈  Пульт студии",true,this::adminEntry),14);}
  private void services(){current=8;page.removeAllViews();title("Что входит","Визуал под ключ","От анализа до файлов для публикации.");String[] names={"01 · Разбор ниши","02 · Структура слайдов","03 · Дизайн и обработка","04 · Согласование","05 · Готовый формат"};String[] lines={"Выделяем преимущества товара и смотрим конкурентов.","Планируем обложку и развитие идеи на каждом слайде.","Работаем с композицией, фоном, иконками и цветом.","Два круга правок по согласованному ТЗ включены.","Отдаём файлы нужного размера для выбранной площадки."};for(int i=0;i<names.length;i++){LinearLayout c=card();add(c,text(names[i],19,WHITE,true),0);add(c,text(lines[i],15,MUTED,false),10);add(page,c,12);}add(page,button("Обсудить проект",true,()->render(3)),20);}
  private void work(){showCases("Все работы");}
  private void showCases(String category){current=1;page.removeAllViews();title("Концепты AuraFX","Детали решают. Рассмотри поближе.","19 демонстрационных концептов. Характеристики на изображениях приведены для примера.");
    HorizontalScrollView row=new HorizontalScrollView(this);row.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);String[] labels={"Все работы","Техника","Красота","Одежда","Для дома","Продукты","Авто","Питомцы","Детям","В дорогу"};for(String label:labels){TextView chip=text(label,13,label.equals(category)?WHITE:MUTED,label.equals(category));chip.setGravity(Gravity.CENTER);chip.setPadding(dp(16),dp(12),dp(16),dp(12));chip.setBackground(label.equals(category)?glow():shape(PANEL,22));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,-2);cp.rightMargin=dp(8);chips.addView(chip,cp);chip.setOnClickListener(v->showCases(label));}row.addView(chips);add(page,row,22);
    int shown=0;for(int i=0;i<CASE_NAMES.length;i++){if(!category.equals("Все работы")&&!CASE_CATEGORIES[i].equals(category))continue;shown++;final int index=i;LinearLayout c=card();c.setPadding(dp(9),dp(9),dp(9),dp(15));ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackground(shape(0xff30233e,18));c.addView(im,new LinearLayout.LayoutParams(-1,dp(265)));image(CASE_COVERS[i],im);add(c,text("✦ AURAFX  /  "+CASE_CATEGORIES[i].toUpperCase(),12,CYAN,true),15);add(c,text(CASE_NAMES[i],21,WHITE,true),7);add(c,text(CASE_DETAILS[i],14,MUTED,false),5);add(c,text("Смотреть кейс · 5 слайдов  ↗",14,WHITE,true),12);add(page,c,16);c.setOnClickListener(v->caseDetail(index,0));enter(c,Math.min(shown*65,500));}add(page,text("Показано: "+shown,13,MUTED,false),17);}
  private String slideFile(int index,int slide){if(index==18)return String.format(java.util.Locale.US,"sweatshirt-slide-%02d.webp",slide+1);if(slide==0)return CASE_COVERS[index];return String.format(java.util.Locale.US,"case-%02d-slide-%02d.webp",index,slide+1);}
  private void caseDetail(int index,int slide){current=7;page.removeAllViews();title(CASE_CATEGORIES[index].toUpperCase()+"  /  AURAFX",CASE_NAMES[index],CASE_DETAILS[index]);ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setBackground(shape(PANEL,20));page.addView(im,new LinearLayout.LayoutParams(-1,dp(420)));image(slideFile(index,slide),im,true);final float[] down={0};im.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){down[0]=e.getX();return true;}if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-down[0];if(Math.abs(dx)>dp(45)){int next=slide+(dx<0?1:-1);if(next>=0&&next<5)caseDetail(index,next);}return true;}return true;});
    add(page,text("Слайд "+(slide+1)+" / 5   ·   листай пальцем",14,CYAN,true),15);LinearLayout dots=new LinearLayout(this);dots.setGravity(Gravity.CENTER);for(int i=0;i<5;i++){TextView dot=text(i==slide?"●":"○",20,i==slide?CYAN:MUTED,false);final int selected=i;dot.setPadding(dp(8),0,dp(8),0);dots.addView(dot);dot.setOnClickListener(v->caseDetail(index,selected));}add(page,dots,5);
    LinearLayout arrows=new LinearLayout(this);arrows.setOrientation(LinearLayout.HORIZONTAL);Button previous=button("← Назад",false,()->caseDetail(index,slide-1));previous.setEnabled(slide>0);Button next=button("Дальше →",true,()->caseDetail(index,slide+1));next.setEnabled(slide<4);arrows.addView(previous,new LinearLayout.LayoutParams(0,dp(54),1));arrows.addView(next,new LinearLayout.LayoutParams(0,dp(54),1));add(page,arrows,11);add(page,button("Хочу похожий дизайн",true,()->render(3)),14);add(page,button("Все работы",false,()->render(1)),10);}
  private void image(String file,ImageView target){image(file,target,false);}
  private void image(String file,ImageView target,boolean full){String key=file+(full?"#full":"#thumb");android.graphics.Bitmap cached=images.get(key);if(cached!=null){target.setImageBitmap(cached);return;}pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+"/"+file).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);try(InputStream in=c.getInputStream()){byte[] bytes=in.readAllBytes();BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=full?1:2;android.graphics.Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);main.post(()->{if(active&&bitmap!=null){images.put(key,bitmap);target.setImageBitmap(bitmap);}});}finally{c.disconnect();}}catch(Exception ignored){main.post(()->{if(active)target.setContentDescription("Изображение временно недоступно");});}});}
  private void prices(){title("Тарифы","Объём и сроки — заранее","Стоимость указана за набор слайдов. Сложную ретушь, 3D и дополнительные форматы оценим после материалов.");String[] names={"Старт","Мини","Серия","Максимум"};String[] amounts={"150 ₽","450 ₽","750 ₽","1 500 ₽"};String[] descriptions={"1 базовая карточка · тест или обложка","3 карточки · короткая серия","5 карточек · подача товара","10 карточек · большой комплект"};int[][] colors={{0xff4b2680,0xff261c45},{0xff214867,0xff34224f},{0xff682fc0,0xff283b85},{0xff783a75,0xff263353}};for(int i=0;i<4;i++){final int count=new int[]{1,3,5,10}[i];LinearLayout c=card();GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,colors[i]);bg.setCornerRadius(dp(24));bg.setStroke(dp(1),0xff79569b);c.setBackground(bg);TextView brand=gradientText("✦ AuraFX",15);add(c,brand,0);floatView(brand,i*130,4);add(c,text(names[i],24,WHITE,true),15);add(c,text(amounts[i],36,WHITE,true),10);add(c,text(descriptions[i],15,0xffe0d4eb,false),8);add(c,button("Выбрать  →",true,()->{render(3);orderCount.setSelection(count==1?0:count==3?1:count==5?2:3);}),18);add(page,c,16);enter(c,100+i*120);}LinearLayout rush=card();add(rush,text("Обычный срок",18,WHITE,true),0);add(rush,text("Ориентир 2–4 дня после получения ТЗ и материалов.",15,MUTED,false),7);add(rush,text("Срочный заказ  ·  +50%",18,CYAN,true),15);add(rush,text("От 24 часов при свободном слоте. Стоимость и время сдачи подтвердим до начала работы.",15,MUTED,false),7);add(rush,text("2 круга правок включены",15,WHITE,true),15);add(page,rush,20);}
  private Spinner orderCount;
  private void order(){title("Заявка","Расскажи о проекте","Заявка попадёт в ту же админку AuraFX, что и заявка с сайта.");EditText product=field("Товар и что нужно показать *",true),contact=field("Контакт: Telegram, телефон или email *",false),style=field("Пожелания по стилю",false),comment=field("Дополнительные детали",true);Spinner market=selector(new String[]{"Wildberries","Ozon","Avito","Яндекс Маркет","Другая площадка"});orderCount=selector(new String[]{"1 карточка · 150 ₽","3 карточки · 450 ₽","5 карточек · 750 ₽","10 карточек · 1 500 ₽","Индивидуально"});Spinner deadline=selector(new String[]{"Обычный · 2–4 дня","Срочный · от 24 часов, +50%"});add(page,text("Площадка",14,MUTED,true),23);add(page,market,7);add(page,text("Тариф",14,MUTED,true),18);add(page,orderCount,7);add(page,text("Срок",14,MUTED,true),18);add(page,deadline,7);add(page,product,18);add(page,style,10);add(page,contact,10);add(page,comment,10);add(page,button("Отправить заявку",true,()->{if(value(product).length()<2||value(contact).length()<3){message("Заполни товар и контакт для связи.");return;}try{JSONObject j=new JSONObject();j.put("marketplace",market.getSelectedItem());j.put("count",new int[]{1,3,5,10,1}[orderCount.getSelectedItemPosition()]);j.put("product",value(product));j.put("style",value(style));j.put("deadline",deadline.getSelectedItemPosition()==1?"Срочный (от 24 часов, доплата +50%, после подтверждения)":"Обычный (ориентир 2–4 дня после ТЗ)");j.put("contact",value(contact));j.put("comment",value(comment)+(orderCount.getSelectedItemPosition()==4?" | Индивидуальный проект":""));j.put("source","android");j.put("medium","native-app");j.put("landing","android://aurafx/order");request("POST","/api/lead",j,(data,e)->{if(e!=null)message(e.getMessage());else{message("Заявка #"+data.optInt("id")+" отправлена");render(5);}});}catch(Exception e){message(e.getMessage());}}),20);add(page,text("Срочный слот и точное время сдачи подтвердим лично до начала работы.",13,MUTED,false),12);}
  private void audit(){current=9;page.removeAllViews();title("Бесплатный mini-audit","Покажи товар — найдём точки роста.","Опиши товар или пришли ссылку. Ответим с идеей обложки и рекомендациями по визуальной подаче.");EditText product=field("Товар или ссылка на карточку *",true),contact=field("Контакт для ответа *",false),notes=field("Что хочется улучшить?",true);add(page,product,22);add(page,contact,10);add(page,notes,10);add(page,button("Отправить на разбор  →",true,()->{if(value(product).length()<2||value(contact).length()<3){message("Укажи товар и контакт для ответа.");return;}try{JSONObject j=new JSONObject();j.put("marketplace","Бесплатный mini-audit");j.put("count",1);j.put("product",value(product));j.put("style","Бесплатный мини-разбор");j.put("deadline","После согласования");j.put("contact",value(contact));j.put("comment",value(notes));j.put("source","android");j.put("medium","native-app");j.put("landing","android://aurafx/audit");request("POST","/api/lead",j,(d,e)->{if(e!=null)message(e.getMessage());else{message("Запрос #"+d.optInt("id")+" отправлен");render(0);}});}catch(Exception e){message(e.getMessage());}}),20);add(page,text("Бесплатно · без регистрации · ответим лично",13,CYAN,true),12);}
  private void quickPlan(){current=10;page.removeAllViews();title("AuraFX Quick Plan","План пяти слайдов за минуту","Используй только реальные преимущества товара. План составляется прямо на телефоне.");EditText product=field("Название товара *",false),benefits=field("Реальные преимущества через запятую *",true);Spinner market=selector(new String[]{"Wildberries","Ozon","Avito","Другая площадка"});add(page,market,19);add(page,product,12);add(page,benefits,10);LinearLayout result=column();add(page,result,15);add(page,button("✦  Собрать план",true,()->{String item=value(product),raw=value(benefits);if(item.length()<2||raw.length()<3){message("Укажи товар и его реальные преимущества.");return;}String[] parts=raw.split("[,;\n]+");java.util.ArrayList<String> valid=new java.util.ArrayList<>();for(String part:parts)if(!part.trim().isEmpty())valid.add(part.trim());if(valid.isEmpty()){message("Добавь хотя бы одно преимущество.");return;}String[] steps={"Обложка · "+item,"Главное преимущество · "+valid.get(0),"Детали товара · "+(valid.size()>1?valid.get(1):"покажи важную деталь"),"Как использовать · покажи товар в деле","Итог · комплектация, размеры и призыв к действию"};result.removeAllViews();StringBuilder copy=new StringBuilder("AuraFX · "+item+" · "+market.getSelectedItem()+"\n");for(int i=0;i<steps.length;i++){LinearLayout c=card();add(c,text(String.format(java.util.Locale.US,"%02d",i+1)+" / 05",12,CYAN,true),0);add(c,text(steps[i],17,WHITE,true),8);add(result,c,10);copy.append(i+1).append(". ").append(steps[i]).append('\n');}add(result,button("Скопировать план",false,()->{ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("AuraFX Quick Plan",copy.toString()));message("План скопирован");}),15);}),17);}
  private void reviews(){current=4;page.removeAllViews();title("Отзывы","Говорят клиенты","Отзывы публикуются через общую систему модерации AuraFX.");LinearLayout form=card();EditText name=field("Ваше имя",false),body=field("Ваш отзыв (от 10 символов)",true);Spinner rating=selector(new String[]{"5 ★","4 ★","3 ★","2 ★","1 ★"});add(form,name,0);add(form,rating,10);add(form,body,10);add(form,button("Отправить отзыв",true,()->{try{JSONObject j=new JSONObject();j.put("name",value(name));j.put("text",value(body));j.put("rating",5-rating.getSelectedItemPosition());request("POST","/api/reviews",j,(d,e)->{if(e!=null)message(e.getMessage());else{message("Спасибо! Отзыв отправлен.");name.setText("");body.setText("");loadReviews();}});}catch(Exception e){message(e.getMessage());}}),12);add(page,form,18);loadReviews();}
  private LinearLayout reviewList;
  private void loadReviews(){if(reviewList!=null)page.removeView(reviewList);reviewList=column();add(page,reviewList,15);request("GET","/api/reviews",null,(d,e)->{if(e!=null){add(reviewList,text("Не удалось загрузить отзывы.",14,MUTED,false),8);return;}JSONArray a=d.optJSONArray("reviews");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(r==null)continue;LinearLayout c=card();add(c,text(r.optString("name","Клиент")+" · "+"★".repeat(Math.max(1,Math.min(5,r.optInt("rating",5)))),16,CYAN,true),0);add(c,text(r.optString("text"),15,WHITE,false),10);add(reviewList,c,12);}});}
  private void account(){title("Кабинет","Ваши заказы","Вход через Telegram связывает заявки с аккаунтом на сайте.");request("GET","/api/auth/me",null,(d,e)->{if(current!=5)return;if(e==null&&d.optBoolean("authenticated")){JSONObject u=d.optJSONObject("user");owner=u!=null&&"admin".equals(u.optString("role"));add(page,text("Привет, "+(u==null?"клиент":u.optString("name","клиент")),20,WHITE,true),20);if(owner)add(page,button("◈  Пульт студии",true,this::adminEntry),12);add(page,button("Поддержка",false,this::support),12);add(page,button("Выйти",false,()->request("POST","/api/auth/logout",new JSONObject(),(x,err)->{session="";owner=false;getPreferences(0).edit().remove("session").apply();render(5);})),10);loadOrders();}else{owner=false;LinearLayout c=card();add(c,text("Войди через @AuraFXAuthBot",19,WHITE,true),0);add(c,text("Подтверди вход в Telegram и вернись в приложение. Заказы и обращения появятся здесь.",15,MUTED,false),12);add(c,button("Войти через Telegram",true,this::startLogin),16);add(page,c,20);}});}
  private void loadOrders(){request("GET","/api/account/leads",null,(d,e)->{if(current!=5)return;if(e!=null){add(page,text("Не удалось загрузить заказы.",14,MUTED,false),18);return;}JSONArray a=d.optJSONArray("orders");add(page,text("Мои заказы",22,WHITE,true),26);if(a==null||a.length()==0){add(page,text("Пока нет заказов. Оставь заявку, и она появится здесь.",15,MUTED,false),12);return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout c=card();add(c,text("#"+o.optInt("id")+" · "+o.optString("product"),17,WHITE,true),0);add(c,text("Статус: "+o.optString("status")+"  ·  "+o.optString("created_at"),13,MUTED,false),8);add(page,c,12);}});}
  private void startLogin(){pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+"/auth/telegram?next=/account").openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(10000);String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new IOException("Не удалось начать вход.");Uri uri=Uri.parse(loc);String token=uri.getQueryParameter("resume");if(token==null||!token.matches("[A-Za-z0-9_-]{20,64}"))throw new IOException("Не удалось получить код входа.");HttpURLConnection ready=(HttpURLConnection)new URL(BASE+loc).openConnection();ready.setConnectTimeout(10000);ready.setReadTimeout(10000);int status=ready.getResponseCode();ready.disconnect();if(status!=200)throw new IOException("Не удалось подключить вход Telegram. Попробуй позже.");loginToken=token;loginTries=0;main.post(()->{Intent intent=new Intent(Intent.ACTION_VIEW,Uri.parse("https://t.me/AuraFXAuthBot?start=login_"+token));try{startActivity(intent);}catch(Exception ex){message("Установи Telegram, чтобы подтвердить вход.");}message("Подтверди вход в Telegram и вернись в AuraFX.");});pollLogin();}catch(Exception e){main.post(()->message(e.getMessage()));}});}
  private void pollLogin(){if(loginToken.isEmpty()||loginTries++>=120)return;request("GET","/api/auth/telegram/status?token="+loginToken+"&remember=1",null,(d,e)->{if(e==null&&d.optBoolean("authenticated")){loginToken="";message("Вход выполнен");render(5);}else if(e==null&&"expired".equals(d.optString("status"))){loginToken="";message("Ссылка входа истекла. Попробуй снова.");}else if(active)main.postDelayed(this::pollLogin,3000);});}
  private void support(){current=6;page.removeAllViews();title("Поддержка","Помощник AuraFX","Ответы по сайту — сразу. Если нужен человек, позови оператора. История общая с сайтом.");add(page,button("Новое обращение",true,this::newSupport),17);request("GET","/api/account/support",null,(d,e)->{if(e!=null){message("Не удалось загрузить обращения.");return;}JSONArray a=d.optJSONArray("threads");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t==null)continue;int id=t.optInt("id");add(page,button("#"+id+" · "+t.optString("subject"),false,()->thread(id)),10);}});}
  private void newSupport(){page.removeAllViews();title("Поддержка","Новый вопрос","Помощник попробует ответить сразу. Вопросы вне базы знаний передаст администратору.");EditText subject=field("Тема",false),body=field("Сообщение",true);add(page,subject,20);add(page,body,10);add(page,button("Отправить",true,()->{try{JSONObject j=new JSONObject();j.put("subject",value(subject));j.put("message",value(body));j.put("category","general");request("POST","/api/account/support",j,(d,e)->{if(e!=null)message(e.getMessage());else thread(d.optInt("id"));});}catch(Exception e){message(e.getMessage());}}),12);}
  private void thread(int id){page.removeAllViews();current=6;title("Поддержка","Чат #"+id,"Ответы помощника и администратора сохраняются в этом диалоге.");LinearLayout messages=column();add(page,messages,12);EditText input=field("Сообщение",true);add(page,input,16);add(page,button("Отправить",true,()->{try{JSONObject j=new JSONObject();j.put("body",value(input));request("POST","/api/account/support/"+id+"/messages",j,(d,e)->{if(e!=null)message(e.getMessage());else thread(id);});}catch(Exception e){message(e.getMessage());}}),10);request("GET","/api/account/support/"+id,null,(d,e)->{if(e!=null){message(e.getMessage());return;}JSONObject t=d.optJSONObject("thread");if(t!=null&&"bot".equals(t.optString("status")))add(page,button("◉  Позвать оператора",false,()->request("POST","/api/account/support/"+id+"/handoff",new JSONObject(),(x,err)->{if(err!=null)message(err.getMessage());else thread(id);})),9);JSONArray a=d.optJSONArray("messages");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;LinearLayout c=card();add(c,text("bot".equals(m.optString("sender_role"))?"✦ Помощник AuraFX":"admin".equals(m.optString("sender_role"))?"Администратор AuraFX":"Вы",13,CYAN,true),0);add(c,text(m.optString("body"),15,WHITE,false),6);add(messages,c,10);}});}
  private void adminEntry(){request("GET","/api/auth/me",null,(d,e)->{JSONObject u=d.optJSONObject("user");owner=e==null&&d.optBoolean("authenticated")&&u!=null&&"admin".equals(u.optString("role"));if(!owner){message("Пульт доступен только владельцу AuraFX. Войди через привязанный Telegram.");render(5);return;}adminDashboard();});}
  private void adminShell(String subtitle){adminGeneration++;current=11;page.removeAllViews();title("AURAFX / OWNER DESK","Пульт студии",subtitle);add(page,button("Сводка",false,this::adminDashboard),12);add(page,button("Заявки",false,this::adminLeads),7);add(page,button("Отзывы",false,this::adminReviews),7);add(page,button("Обращения",false,this::adminSupport),7);}
  private String statusName(String status){switch(status){case "new":return "Новая";case "contacted":return "В работе";case "review":return "На согласовании";case "revision":return "Правки";case "done":return "Готово";case "spam":return "Закрыта";default:return status;}}
  private void adminDashboard(){adminShell("Сегодня в студии · данные сайта и приложения в одном месте");LinearLayout summary=card();summary.setBackground(glow());add(summary,text("ОБЗОР СЕГОДНЯ",12,CYAN,true),0);LinearLayout numbers=column();add(summary,numbers,13);add(page,summary,20);int generation=adminGeneration;request("GET","/api/admin/dashboard",null,(d,e)->{if(current!=11||generation!=adminGeneration)return;if(e!=null){message(e.getMessage());return;}JSONObject m=d.optJSONObject("metrics");if(m==null)return;add(numbers,text(m.optInt("leads_today")+"  новых заявок",25,WHITE,true),0);add(numbers,text(m.optInt("pending_reviews")+" отзывов ждут решения  ·  "+m.optInt("online")+" сейчас на сайте",14,WHITE,false),10);add(numbers,text(m.optInt("today_unique")+" посетителей сегодня",14,WHITE,false),7);});add(page,text("БЫСТРЫЕ ДЕЙСТВИЯ",12,CYAN,true),24);add(page,button("Разобрать заявки  ↗",true,this::adminLeads),10);add(page,button("Ответить клиентам",false,this::adminSupport),8);add(page,button("Проверить отзывы",false,this::adminReviews),8);}
  private void adminLeads(){adminShell("Очередь заказов · смена статуса сразу видна клиенту");LinearLayout list=column();add(page,list,17);int generation=adminGeneration;request("GET","/api/admin/leads",null,(d,e)->{if(current!=11||generation!=adminGeneration)return;if(e!=null){message(e.getMessage());return;}JSONArray a=d.optJSONArray("leads");if(a==null||a.length()==0){add(list,text("Заявок пока нет.",15,MUTED,false),0);return;}for(int i=0;i<a.length();i++){JSONObject lead=a.optJSONObject(i);if(lead==null)continue;int id=lead.optInt("id");LinearLayout c=card();add(c,text("#"+id+"  /  "+statusName(lead.optString("status")),12,CYAN,true),0);add(c,text(lead.optString("product","Проект"),20,WHITE,true),7);add(c,text(lead.optString("marketplace")+" · "+lead.optInt("count")+" шт. · "+lead.optString("deadline"),13,MUTED,false),7);add(c,text("Контакт: "+lead.optString("contact","—"),14,WHITE,false),11);String note=lead.optString("comment");if(!note.isEmpty())add(c,text(note,14,MUTED,false),7);add(c,button("Открыть и изменить статус",false,()->adminLeadDetail(lead)),12);add(list,c,12);}});}
  private void adminLeadDetail(JSONObject lead){adminShell("Заявка #"+lead.optInt("id"));add(page,text(lead.optString("product"),24,WHITE,true),19);String[] keys={"marketplace","count","style","deadline","contact","comment","client_comment","source","created_at"};String[] labels={"Площадка","Карточек","Стиль","Срок","Контакт","Комментарий","Правки клиента","Источник","Создано"};LinearLayout detail=card();for(int i=0;i<keys.length;i++){String value=lead.optString(keys[i],"");if(!value.isEmpty()&&!value.equals("null"))add(detail,text(labels[i]+": "+value,14,i==4?WHITE:MUTED,i==4),i==0?0:8);}add(page,detail,15);add(page,text("ЭТАП ЗАКАЗА",12,CYAN,true),22);String[] codes={"new","contacted","review","revision","done","spam"};for(String code:codes){add(page,button((code.equals(lead.optString("status"))?"✓  ":"○  ")+statusName(code),false,()->new android.app.AlertDialog.Builder(this).setTitle("Изменить статус?").setMessage("Заявка #"+lead.optInt("id")+" → "+statusName(code)+". Клиент может получить уведомление.").setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(dialog,which)->{try{JSONObject body=new JSONObject();body.put("status",code);request("PATCH","/api/admin/leads/"+lead.optInt("id"),body,(d,e)->{if(e!=null)message(e.getMessage());else{message("Статус сохранён");adminLeads();}});}catch(Exception e){message(e.getMessage());}}).show()),8);}}
  private void adminReviews(){adminShell("Модерация · публикация в общей ленте AuraFX");LinearLayout list=column();add(page,list,17);int generation=adminGeneration;request("GET","/api/admin/reviews",null,(d,e)->{if(current!=11||generation!=adminGeneration)return;if(e!=null){message(e.getMessage());return;}JSONArray a=d.optJSONArray("reviews");if(a==null||a.length()==0){add(list,text("Отзывов пока нет.",15,MUTED,false),0);return;}for(int i=0;i<a.length();i++){JSONObject review=a.optJSONObject(i);if(review==null)continue;int id=review.optInt("id");LinearLayout c=card();add(c,text("#"+id+" · "+review.optString("status")+" · "+"★".repeat(Math.max(1,Math.min(5,review.optInt("rating",5)))),13,CYAN,true),0);add(c,text(review.optString("name","Клиент"),18,WHITE,true),7);add(c,text(review.optString("text"),15,MUTED,false),8);if(!"approved".equals(review.optString("status")))add(c,button("Опубликовать",true,()->adminReviewStatus(id,"approved")),10);if(!"hidden".equals(review.optString("status")))add(c,button("Скрыть",false,()->adminReviewStatus(id,"hidden")),7);add(list,c,12);}});}
  private void adminReviewStatus(int id,String status){try{JSONObject body=new JSONObject();body.put("status",status);request("PATCH","/api/admin/reviews/"+id,body,(d,e)->{if(e!=null)message(e.getMessage());else adminReviews();});}catch(Exception e){message(e.getMessage());}}
  private void adminSupport(){adminShell("Диалоги с клиентами · ответы придут в их кабинет");LinearLayout list=column();add(page,list,15);int generation=adminGeneration;request("GET","/api/admin/support",null,(d,e)->{if(current!=11||generation!=adminGeneration)return;if(e!=null){message(e.getMessage());return;}JSONArray a=d.optJSONArray("threads");if(a==null||a.length()==0){add(list,text("Обращений пока нет.",15,MUTED,false),0);return;}for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t==null)continue;int id=t.optInt("id");add(list,button("#"+id+" · "+t.optString("subject")+("open".equals(t.optString("status"))?"  ·  Нужен ответ":"")+(t.optInt("unread")>0?"  ●":""),false,()->adminThread(id)),10);}});}
  private void adminThread(int id){adminShell("Обращение #"+id);LinearLayout list=column();add(page,list,14);EditText answer=field("Ответ клиенту",true);add(page,answer,18);add(page,button("Отправить ответ",true,()->{if(value(answer).isEmpty())return;try{JSONObject body=new JSONObject();body.put("body",value(answer));request("POST","/api/admin/support/"+id+"/messages",body,(d,e)->{if(e!=null)message(e.getMessage());else adminThread(id);});}catch(Exception e){message(e.getMessage());}}),8);add(page,button("Отметить решённым",false,()->{try{JSONObject body=new JSONObject();body.put("status","resolved");request("PATCH","/api/admin/support/"+id,body,(d,e)->{if(e!=null)message(e.getMessage());else adminSupport();});}catch(Exception e){message(e.getMessage());}}),8);int generation=adminGeneration;request("GET","/api/admin/support/"+id,null,(d,e)->{if(current!=11||generation!=adminGeneration)return;if(e!=null){message(e.getMessage());return;}JSONArray a=d.optJSONArray("messages");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;LinearLayout c=card();add(c,text("bot".equals(m.optString("sender_role"))?"✦ Помощник":"admin".equals(m.optString("sender_role"))?"Вы / AuraFX":"Клиент",12,CYAN,true),0);add(c,text(m.optString("body"),15,WHITE,false),6);add(list,c,9);}});}
  private void request(String method,String path,JSONObject body,Done done){pool.execute(()->{JSONObject result=null;Exception error=null;HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Accept","application/json");if(!session.isEmpty())c.setRequestProperty("Cookie",session);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();String cookie=c.getHeaderField("Set-Cookie");if(cookie!=null&&cookie.startsWith("afx_user=")){session=cookie.split(";",2)[0];getPreferences(0).edit().putString("session",session).apply();}InputStream stream=code>=400?c.getErrorStream():c.getInputStream();String raw=stream==null?"{}":new String(stream.readAllBytes(),StandardCharsets.UTF_8);if(stream!=null)stream.close();result=new JSONObject(raw);if(code>=400)throw new IOException(result.optString("error","Сервер ответил: "+code));}catch(Exception ex){error=ex;}finally{if(c!=null)c.disconnect();}JSONObject d=result;Exception e=error;main.post(()->{if(active)done.accept(d==null?new JSONObject():d,e);});});}
}
