package ru.aurafx.design;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.content.Intent;
import android.net.Uri;
import android.graphics.Color;
import android.graphics.BitmapFactory;
import android.graphics.drawable.GradientDrawable;
import android.view.View;
import android.view.Gravity;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.net.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.*;

public class MainActivity extends Activity {
  private static final String BASE="https://aurafx-design.ru";
  private static final int BG=0xff0c0715, PANEL=0xff1d142c, WHITE=0xfff8f3ff, MUTED=0xffbaaccb, VIOLET=0xff9b4dff, CYAN=0xff70e6f6;
  private final ExecutorService pool=Executors.newFixedThreadPool(3);
  private final Handler main=new Handler(Looper.getMainLooper());
  private LinearLayout page,root,nav;
  private String session="", loginToken="";
  private int current=0, loginTries=0;
  private boolean active=true;
  private interface Done { void accept(JSONObject data, Exception error); }

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);session=getPreferences(0).getString("session","");render(0);}
  @Override protected void onDestroy(){active=false;pool.shutdownNow();super.onDestroy();}
  @Override public void onBackPressed(){if(current!=0)render(0);else super.onBackPressed();}
  private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  private GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));g.setStroke(dp(1),0xff453453);return g;}
  private GradientDrawable glow(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff682abe,0xff302358,0xff14506b});g.setCornerRadius(dp(24));return g;}
  private TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(null,1);t.setLineSpacing(dp(3),1);return t;}
  private void add(LinearLayout box,View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(top);box.addView(v,p);}
  private LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);return c;}
  private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(shape(PANEL,22));return c;}
  private void title(String kicker,String heading,String sub){add(page,text(kicker.toUpperCase(),12,CYAN,true),8);add(page,text(heading,32,WHITE,true),10);if(sub!=null)add(page,text(sub,15,MUTED,false),9);}
  private Button button(String label,boolean primary,Runnable action){Button b=new Button(this);b.setAllCaps(false);b.setText(label);b.setTextSize(15);b.setTextColor(WHITE);b.setBackground(primary?glow():shape(0xff292035,16));b.setOnClickListener(v->action.run());return b;}
  private EditText field(String hint,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(0xff8f81a0);e.setTextColor(WHITE);e.setTextSize(15);e.setSingleLine(!multi);if(multi)e.setMinLines(3);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(shape(0xff261d32,14));return e;}
  private Spinner selector(String[] values){Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values);s.setAdapter(a);s.setBackground(shape(0xff30213f,14));s.setPadding(dp(12),dp(8),dp(12),dp(8));return s;}
  private String value(EditText e){return e.getText().toString().trim();}
  private void message(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
  private void render(int tab){current=tab;root=column();root.setBackgroundColor(BG);setContentView(root);TextView logo=text("✦ AuraFX",23,WHITE,true);logo.setPadding(dp(22),dp(18),dp(22),dp(12));root.addView(logo);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);page=column();page.setPadding(dp(20),0,dp(20),dp(24));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(0xff191124);String[] tabs={"Главная","Работы","Тарифы","Заявка","Кабинет"};for(int i=0;i<tabs.length;i++){final int index=i;TextView item=text(tabs[i],11,i==tab?CYAN:MUTED,i==tab);item.setGravity(Gravity.CENTER);item.setPadding(0,dp(17),0,dp(17));nav.addView(item,new LinearLayout.LayoutParams(0,-2,1));item.setOnClickListener(v->render(index));}root.addView(nav);switch(tab){case 0:home();break;case 1:work();break;case 2:prices();break;case 3:order();break;default:account();}}
  private void home(){title("Дизайн карточек товара","Товар есть. Теперь ему нужен вид.","Продающая инфографика для маркетплейсов. От идеи до готовых слайдов — в AuraFX.");LinearLayout hero=card();hero.setBackground(glow());add(hero,text("Карточки, которые хочется рассмотреть",23,WHITE,true),4);add(hero,text("Реальные кейсы, прозрачные тарифы и связь по заказу в одном приложении.",15,WHITE,false),12);add(hero,button("Обсудить проект →",true,()->render(3)),16);add(page,hero,24);add(page,text("Что мы делаем",22,WHITE,true),30);String[] items={"✦ Инфографика для Wildberries, Ozon и Avito","✦ Обложки и серии слайдов","✦ Адаптация под стиль вашего бренда"};for(String x:items){LinearLayout c=card();add(c,text(x,16,WHITE,true),0);add(page,c,10);}add(page,button("Смотреть работы",false,()->render(1)),20);add(page,button("Отзывы клиентов",false,this::reviews),10);}
  private void work(){title("Портфолио","Результат в деталях","Примеры дизайна AuraFX. Изображения загружаются с общего сайта.");String[] names={"Кисти для макияжа","Автомобильный пылесос","Кормушка для питомца","Подушка с эффектом памяти","Магнитный конструктор","Термокружка","Одежда"};String[] files={"face-brush.webp","car-vacuum.webp","pet-feeder.webp","memory-pillow.webp","magnetic-builder.webp","travel-mug.webp","sweatshirt-slide-01.webp"};for(int i=0;i<files.length;i++){LinearLayout c=card();ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackground(shape(0xff30233e,18));c.addView(im,new LinearLayout.LayoutParams(-1,dp(220)));image(files[i],im);add(c,text(names[i],19,WHITE,true),13);add(page,c,16);}}
  private void image(String file,ImageView target){pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+"/"+file).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);try(InputStream in=c.getInputStream()){byte[] bytes=in.readAllBytes();android.graphics.Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length);main.post(()->{if(active&&bitmap!=null)target.setImageBitmap(bitmap);});}finally{c.disconnect();}}catch(Exception ignored){}});}
  private void prices(){title("Тарифы","Выбирай свой масштаб","Стоимость указана за набор слайдов. Сложную ретушь и 3D оценим после просмотра материалов.");String[] names={"Старт","Мини","Серия","Максимум"};String[] amounts={"150 ₽","450 ₽","750 ₽","1 500 ₽"};String[] descriptions={"1 базовая карточка","3 карточки для короткой серии","5 карточек для подачи товара","10 карточек — большой комплект"};for(int i=0;i<4;i++){final int count=new int[]{1,3,5,10}[i];LinearLayout c=card();if(i==2)c.setBackground(glow());add(c,text("✦ AuraFX",14,CYAN,true),0);add(c,text(names[i],22,WHITE,true),12);add(c,text(amounts[i],32,WHITE,true),12);add(c,text(descriptions[i],15,MUTED,false),9);add(c,button("Выбрать",true,()->{render(3);orderCount.setSelection(count==1?0:count==3?1:count==5?2:3);}),15);add(page,c,15);}LinearLayout rush=card();add(rush,text("Обычный срок · 2–4 дня",17,WHITE,true),0);add(rush,text("Срочно · от 24 часов, доплата +50% после подтверждения свободного слота.",15,MUTED,false),12);add(rush,text("2 круга правок по согласованному ТЗ включены.",14,CYAN,false),12);add(page,rush,18);}
  private Spinner orderCount;
  private void order(){title("Заявка","Расскажи о проекте","Заявка попадёт в ту же админку AuraFX, что и заявка с сайта.");EditText product=field("Товар и что нужно показать *",true),contact=field("Контакт: Telegram, телефон или email *",false),style=field("Пожелания по стилю",false),comment=field("Дополнительные детали",true);Spinner market=selector(new String[]{"Wildberries","Ozon","Avito","Яндекс Маркет","Другая площадка"});orderCount=selector(new String[]{"1 карточка · 150 ₽","3 карточки · 450 ₽","5 карточек · 750 ₽","10 карточек · 1 500 ₽","Индивидуально"});Spinner deadline=selector(new String[]{"Обычный · 2–4 дня","Срочный · от 24 часов, +50%"});add(page,text("Площадка",14,MUTED,true),23);add(page,market,7);add(page,text("Тариф",14,MUTED,true),18);add(page,orderCount,7);add(page,text("Срок",14,MUTED,true),18);add(page,deadline,7);add(page,product,18);add(page,style,10);add(page,contact,10);add(page,comment,10);add(page,button("Отправить заявку",true,()->{if(value(product).length()<2||value(contact).length()<3){message("Заполни товар и контакт для связи.");return;}try{JSONObject j=new JSONObject();j.put("marketplace",market.getSelectedItem());j.put("count",new int[]{1,3,5,10,1}[orderCount.getSelectedItemPosition()]);j.put("product",value(product));j.put("style",value(style));j.put("deadline",deadline.getSelectedItemPosition()==1?"Срочный (от 24 часов, доплата +50%, после подтверждения)":"Обычный (ориентир 2–4 дня после ТЗ)");j.put("contact",value(contact));j.put("comment",value(comment)+(orderCount.getSelectedItemPosition()==4?" | Индивидуальный проект":""));j.put("source","android");j.put("medium","native-app");j.put("landing","android://aurafx/order");request("POST","/api/lead",j,(data,e)->{if(e!=null)message(e.getMessage());else{message("Заявка #"+data.optInt("id")+" отправлена");render(4);}});}catch(Exception e){message(e.getMessage());}}),20);add(page,text("Срочный слот и точное время сдачи подтвердим лично до начала работы.",13,MUTED,false),12);}
  private void reviews(){current=5;page.removeAllViews();title("Отзывы","Говорят клиенты","Отзывы публикуются через общую систему модерации AuraFX.");LinearLayout form=card();EditText name=field("Ваше имя",false),body=field("Ваш отзыв (от 10 символов)",true);Spinner rating=selector(new String[]{"5 ★","4 ★","3 ★","2 ★","1 ★"});add(form,name,0);add(form,rating,10);add(form,body,10);add(form,button("Отправить отзыв",true,()->{try{JSONObject j=new JSONObject();j.put("name",value(name));j.put("text",value(body));j.put("rating",5-rating.getSelectedItemPosition());request("POST","/api/reviews",j,(d,e)->{if(e!=null)message(e.getMessage());else{message("Спасибо! Отзыв отправлен.");name.setText("");body.setText("");loadReviews();}});}catch(Exception e){message(e.getMessage());}}),12);add(page,form,18);loadReviews();}
  private LinearLayout reviewList;
  private void loadReviews(){if(reviewList!=null)page.removeView(reviewList);reviewList=column();add(page,reviewList,15);request("GET","/api/reviews",null,(d,e)->{if(e!=null){add(reviewList,text("Не удалось загрузить отзывы.",14,MUTED,false),8);return;}JSONArray a=d.optJSONArray("reviews");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(r==null)continue;LinearLayout c=card();add(c,text(r.optString("name","Клиент")+" · "+"★".repeat(Math.max(1,Math.min(5,r.optInt("rating",5)))),16,CYAN,true),0);add(c,text(r.optString("text"),15,WHITE,false),10);add(reviewList,c,12);}});}
  private void account(){title("Кабинет","Ваши заказы","Вход через Telegram связывает заявки с аккаунтом на сайте.");request("GET","/api/auth/me",null,(d,e)->{if(current!=4)return;if(e==null&&d.optBoolean("authenticated")){JSONObject u=d.optJSONObject("user");add(page,text("Привет, "+(u==null?"клиент":u.optString("name","клиент")),20,WHITE,true),20);add(page,button("Поддержка",false,this::support),12);add(page,button("Выйти",false,()->request("POST","/api/auth/logout",new JSONObject(),(x,err)->{session="";getPreferences(0).edit().remove("session").apply();render(4);})),10);loadOrders();}else{LinearLayout c=card();add(c,text("Войди через @AuraFXAuthBot",19,WHITE,true),0);add(c,text("Подтверди вход в Telegram и вернись в приложение. Заказы и обращения появятся здесь.",15,MUTED,false),12);add(c,button("Войти через Telegram",true,this::startLogin),16);add(page,c,20);}});}
  private void loadOrders(){request("GET","/api/account/leads",null,(d,e)->{if(current!=4)return;if(e!=null){add(page,text("Не удалось загрузить заказы.",14,MUTED,false),18);return;}JSONArray a=d.optJSONArray("orders");add(page,text("Мои заказы",22,WHITE,true),26);if(a==null||a.length()==0){add(page,text("Пока нет заказов. Оставь заявку, и она появится здесь.",15,MUTED,false),12);return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout c=card();add(c,text("#"+o.optInt("id")+" · "+o.optString("product"),17,WHITE,true),0);add(c,text("Статус: "+o.optString("status")+"  ·  "+o.optString("created_at"),13,MUTED,false),8);add(page,c,12);}});}
  private void startLogin(){pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+"/auth/telegram?next=/account").openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(10000);String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new IOException("Не удалось начать вход.");Uri uri=Uri.parse(loc);String token=uri.getQueryParameter("resume");if(token==null||!token.matches("[A-Za-z0-9_-]{20,64}"))throw new IOException("Не удалось получить код входа.");loginToken=token;loginTries=0;main.post(()->{Intent intent=new Intent(Intent.ACTION_VIEW,Uri.parse("https://t.me/AuraFXAuthBot?start=login_"+token));try{startActivity(intent);}catch(Exception ex){message("Установи Telegram, чтобы подтвердить вход.");}message("Подтверди вход в Telegram и вернись в AuraFX.");});pollLogin();}catch(Exception e){main.post(()->message(e.getMessage()));}});}
  private void pollLogin(){if(loginToken.isEmpty()||loginTries++>=120)return;request("GET","/api/auth/telegram/status?token="+loginToken+"&remember=1",null,(d,e)->{if(e==null&&d.optBoolean("authenticated")){loginToken="";message("Вход выполнен");render(4);}else if(e==null&&"expired".equals(d.optString("status"))){loginToken="";message("Ссылка входа истекла. Попробуй снова.");}else if(active)main.postDelayed(this::pollLogin,3000);});}
  private void support(){current=6;page.removeAllViews();title("Поддержка","Мы на связи","Переписка общая с личным кабинетом сайта.");add(page,button("Новое обращение",true,this::newSupport),17);request("GET","/api/account/support",null,(d,e)->{if(e!=null){message("Не удалось загрузить обращения.");return;}JSONArray a=d.optJSONArray("threads");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t==null)continue;int id=t.optInt("id");add(page,button("#"+id+" · "+t.optString("subject"),false,()->thread(id)),10);}});}
  private void newSupport(){page.removeAllViews();title("Поддержка","Новое обращение",null);EditText subject=field("Тема",false),body=field("Сообщение",true);add(page,subject,20);add(page,body,10);add(page,button("Отправить",true,()->{try{JSONObject j=new JSONObject();j.put("subject",value(subject));j.put("message",value(body));j.put("category","general");request("POST","/api/account/support",j,(d,e)->{if(e!=null)message(e.getMessage());else thread(d.optInt("id"));});}catch(Exception e){message(e.getMessage());}}),12);}
  private void thread(int id){page.removeAllViews();current=6;title("Поддержка","Обращение #"+id,null);LinearLayout messages=column();add(page,messages,12);EditText input=field("Сообщение",true);add(page,input,16);add(page,button("Отправить",true,()->{try{JSONObject j=new JSONObject();j.put("body",value(input));request("POST","/api/account/support/"+id+"/messages",j,(d,e)->{if(e!=null)message(e.getMessage());else thread(id);});}catch(Exception e){message(e.getMessage());}}),10);request("GET","/api/account/support/"+id,null,(d,e)->{if(e!=null){message(e.getMessage());return;}JSONArray a=d.optJSONArray("messages");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;LinearLayout c=card();add(c,text("admin".equals(m.optString("sender_role"))?"AuraFX":"Вы",13,CYAN,true),0);add(c,text(m.optString("body"),15,WHITE,false),6);add(messages,c,10);}});}
  private void request(String method,String path,JSONObject body,Done done){pool.execute(()->{JSONObject result=null;Exception error=null;HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Accept","application/json");if(!session.isEmpty())c.setRequestProperty("Cookie",session);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();String cookie=c.getHeaderField("Set-Cookie");if(cookie!=null&&cookie.startsWith("afx_user=")){session=cookie.split(";",2)[0];getPreferences(0).edit().putString("session",session).apply();}InputStream stream=code>=400?c.getErrorStream():c.getInputStream();String raw=stream==null?"{}":new String(stream.readAllBytes(),StandardCharsets.UTF_8);if(stream!=null)stream.close();result=new JSONObject(raw);if(code>=400)throw new IOException(result.optString("error","Сервер ответил: "+code));}catch(Exception ex){error=ex;}finally{if(c!=null)c.disconnect();}JSONObject d=result;Exception e=error;main.post(()->{if(active)done.accept(d==null?new JSONObject():d,e);});});}
}
